In [18]:
import pandas as pd
from bs4 import BeautifulSoup
from urllib.parse import urlencode
import requests

# 网页提取函数
def get_one_page(i):
	headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36'
        }
	paras = {
	'reportTime': '2017-12-31',   
	#可以改报告日期，比如2018-6-30获得的就是该季度的信息
	'pageNum': i   #页码
	}
	url = 'http://s.askci.com/stock/a/?' + urlencode(paras)
	response = requests.get(url,headers = headers)
	if response.status_code == 200:
		return response.text
	return None

# beatutiful soup解析然后提取表格
def parse_one_page(html):
	soup = BeautifulSoup(html,'lxml')
	content = soup.select('#myTable04')[0] #[0]将返回的list改为bs4类型
	tbl = pd.read_html(content.prettify(),header = 0)[0]
	# prettify()优化代码,[0]从pd.read_html返回的list中提取出DataFrame
	
	tbl.rename(columns = {'序号':'serial_number', '股票代码':'stock_code', '股票简称':'stock_abbre', '公司名称':'company_name', '省份':'province', '城市':'city', '主营业务收入(201712)':'main_bussiness_income', '净利润(201712)':'net_profit', '员工人数':'employees', '上市日期':'listing_date', '招股书':'zhaogushu', '公司财报':'financial_report', '行业分类':'industry_classification', '产品类型':'industry_type', '主营业务':'main_business'},inplace = True)
	
	print(tbl)
	tbl.to_html("123.html")

	# return tbl
	# rename将表格15列的中文名改为英文名，便于存储到mysql及后期进行数据分析
	# tbl = pd.DataFrame(tbl,dtype = 'object') #dtype可统一修改列格式为文本
    
# 主函数
def main(page):
	for i in range(1,page):   # page表示提取页数
		html = get_one_page(i)
		parse_one_page(html)

# 单进程
if __name__ == '__main__':	
	main(5)   #共提取n页

    serial_number  stock_code stock_abbre       company_name province city  \
0               1           1        平安银行         平安银行股份有限公司       广东  深圳市
1               2           2         万科A         万科企业股份有限公司       广东  深圳市
2               3           4        国农科技     深圳中国农大科技股份有限公司       广东  深圳市
3               4           5        世纪星源       深圳世纪星源股份有限公司       广东  深圳市
4               5           6        深振业A    深圳市振业(集团)股份有限公司       广东  深圳市
5               6           7         全新好       深圳市全新好股份有限公司       广东  深圳市
6               7           8        神州高铁       神州高铁技术股份有限公司       北京  北京市
7               8           9        中国宝安       中国宝安集团股份有限公司       广东  深圳市
8               9          10        美丽生态       深圳美丽生态股份有限公司       广东  深圳市
9              10          11        深物业A  深圳市物业发展(集团)股份有限公司       广东  深圳市
10             11          12         南玻A       中国南玻集团股份有限公司       广东  深圳市
11             12          14        沙河股份         沙河实业股份有限公司       广东  深圳市
12             13          16        深康佳A         康佳集团股份有限公司       广东  深圳市
13             14          17        深中华A  深圳中华自行车(集团)股份有限公司       广东  深圳市
14             15          18        神州长城         神州长城股份有限公司       广东  深圳市
15             16          19        深深宝A      深圳市深宝实业股份有限公司       广东  深圳市
16             17          20        深华发A       深圳中恒华发股份有限公司       广东  深圳市
17             18          21         深科技     深圳长城开发科技股份有限公司       广东  深圳市
18             19          22        深赤湾A       深圳赤湾港航股份有限公司       广东  深圳市
19             20          23        深天地A    深圳市天地(集团)股份有限公司       广东  深圳市

    main_bussiness_income  net_profit  employees listing_date zhaogushu  \
0             10578600.00  2318900.00      32744   1991-04-03        --
1             24289711.03  2805181.49      92764   1991-01-29        --
2                13860.58      856.67        172   1991-01-14        --
3                53092.22     1530.84        705   1990-12-10        --
4               295945.02    80563.64        370   1992-04-27        --
5                 3964.40     1645.37        102   1992-04-13        --
6               233093.22    87378.05       2417   1992-05-07        --
7               702351.12    13320.38      10944   1991-06-25        --
8                75788.57  -106142.69        489   1995-10-27        --
9               290469.07    62296.27       5196   1992-03-30        --
10             1087940.07    82538.83      12105   1992-02-28        --
11               51314.10      763.03        156   1992-06-02        --
12             3122776.32   505702.52      17822   1992-03-27        --
13               13749.06      152.96         51   1992-03-31        --
14              649712.50    38009.10       2875   1992-06-16        --
15               31576.27    -5409.41        688   1992-10-12        --
16               85804.01       97.44        993   1992-04-28        --
17             1420977.86    54130.30      24626   1994-02-02        --
18              245621.88    50449.51       1719   1993-05-05        --
19              122918.71     3050.08       1123   1993-04-29        --

    financial_report industry_classification                   industry_type  \
0                NaN                      银行                          商业银行业务
1                NaN                   房地产开发                   房地产、物业管理、投资咨询
2                NaN                    生物医药                          生物医药业务
3                NaN               环保工程、物业管理              酒店经营、物业管理收入、环保业务收入
4                NaN                   房地产开发                       物业租赁、房产销售
5                NaN                    物业经营                   物业管理及停车费、房屋租赁
6                NaN                  轨道交通设备                       轨道交通、酒店服务
7                NaN                      综合                 高新技术产业、生物医药、房地产
8                NaN                    园林工程           燃气销售服务、园林建设、园林设计、苗木销售
9                NaN                   房地产开发       房地产开发、房屋租赁、物业管理、交通运输、饮食服务
10               NaN                      玻璃                        玻璃、太阳能产品
11               NaN                   房地产开发              房地产销售、物业管理、代建、综合服务
12               NaN                     电视机                        电子、供应链管理
13               NaN                     自行车                 自行车及零配件销售、锂电池材料
14               NaN                    装修装饰               装饰工程施工、工程总承包、工程设计
15               NaN                     软饮料                 工业、贸易、房地产、租赁服务业
16               NaN                   电子零部件                     显示器、注塑件、泡沫件
17               NaN               PC、服务器及硬件               硬盘相关产品、自有产品、OEM产品
18               NaN                      港口  装卸业务、港口配套业务、代理及其他业务、各业务分部间互相抵消
19               NaN                   商品混凝土                          房地产、建材

                                        main_business
0                                  经有关监管机构批准的各项商业银行业务
1                                          房地产开发和物业服务
2                                                生物制药
3                                   绿色低碳城市社区建设相关的服务业务
4                                          从事房地产开发与销售
5                                         物业管理和房屋租赁业等
6             专业致力于为轨道交通安全运营提供监测、检测、维修、保养设备和服务及整体解决方案
7                   新能源、新材料及其它高新技术产业、生物医药业、房地产业以及其他行业
8                      从事苗木种植、园林绿化工程施工和养护为一体的综合性园林服务。
9                   从事房地产开发经营，兼营物业管理、房屋租赁、出租车客运、餐饮服务等
10  平板玻璃、工程玻璃等节能建筑材料,硅材料、光伏组件等可再生能源产品及超薄电子玻璃等新型材料和...
11                                           房地产开发和销售
12                               彩电业务、手机业务、白电业务、供应链贸易
13                         电动自行车、自行车及零配件的生产和销售以及物业管理。
14                               建筑装饰工程设计与施工及建筑相关工程施工
15                                             食品饮料行业
16      精密注塑件的加工、销售;液晶显示器的加工、销售;轻型包装材料的加工、销售以及物业租赁业务。
17                                       计算机硬件、通讯设备等。
18                          集装箱和散杂货的港口装卸、仓储、运输及其它配套服务
19                                混凝土的生产和销售、房地产的开发与销售

NameError: name 'tb1' is not defined